#!/bin/bash

function build-classpath() {

    local lib_dir=$(dirname $0)/../lib

    [ -d ${lib_dir} ] || { echo "library directory ${lib_dir} not found" 1>&2; exit 1; }

    local classpath="";

    for i in $(find ${lib_dir} -name *.jar); do
        [ -z "${classpath}" ] && classpath=${i} || classpath=${classpath}:${i}
    done

    [ -z "${classpath}" ] && { echo "no jar files found in ${lib_dir}" 1>&2; exit 1; }

    #
    # place the directory itself (and the log4j.xml) at the front of the classpath
    #

    classpath="${lib_dir}:${classpath}"

    echo ${classpath}
}

function main() {

    local debug=""

    while [ -n "$1" ]; do

        if [ "$1" = "-d" -o "$1" = "--debug" ]; then
            debug="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5005"
        fi
        shift
    done

    local classpath
    classpath=$(build-classpath) || exit 1

    java ${debug} -cp ${classpath} io.novaordis.gld.Main

}

main $@