#!/bin/bash
#
# Installs cld on /opt/mobileapps share available to PROD
#

[ -f $(dirname $0)/install.shlib ] && . $(dirname $0)/install.shlib || { echo "library file $(dirname $0)/install.shlib not found" 1>&2; exit 1; }

user=devuser

install_over_ssh 10.98.9.190 ${user} $@
install_over_ssh 10.98.9.67 ${user} $@
