#!/bin/bash

messages=10
threads=1
queue=TEST
nodes="localhost:61616"
type=send
output=./send.csv

if [ "${type}" = receive ]; then service_args="--service activemq"
elif [ "${type}" = send ]; then service_args="--service com.novaordis.gld.service.jms.activemq.CollocatedBrokerService --memoryUsage 500mb --directory /Users/ovidiu/tmp/gld-activemq --delete-directory-at-boot"
else echo "unknown type ${type}" 1>&2; exit 1; fi

[ ! -z ${output} ] && output_option="--output ${output}"

while [ -n "$1" ]; do
    [ "$1" = "--debug" ] && debug_arg="--debug"
    shift
done

gld ${debug_arg} load \
--nodes "${nodes}" \
--max-operations ${messages} \
--threads ${threads} \
${service_args} \
--load-strategy ${type} \
--queue ${queue} \
${output_option} \
--username admin --password admin123

