#!/bin/bash
#
# Cache content analyzer.
#
# Run ./cld for help.
#
#

reldir=$(dirname $0)
home_dir=${reldir}/..

function get_java_home()
{
    # we cannot rely on JAVA_HOME in J4, so we hardcode
    local java_home="/usr/java/jdk64-1.7.0_45"

    local name;
    name=$(uname -n)
    name=${name##*.}

    [ "${name}" = "local" -o "${name}" = "ovidius-mbp" ] && java_home="/Library/Java/JavaVirtualMachines/jdk1.7.0_60.jdk/Contents/Home"

    echo ${java_home}
}

function get_classpath()
{
    local first=true
    for i in ${home_dir}/lib/*.jar; do
        ${first} && first=false || echo -n ":"
        echo -n ${i}
    done
}

java_home=$(get_java_home) || { echo "failed to get JAVA_HOME"; exit 1; }
classpath=$(get_classpath) || { echo "failed to build classpath"; exit 1; }

debug_args=""
output_settings=""

while [ "$1" != "" ]; do
    if [ "$1" = "--debug" ]; then
        debug_args="-agentlib:jdwp=transport=dt_socket,server=y,suspend=y,address=5011"
    else
        args="${args} $1"
    fi
    shift;
done

${java_home}/bin/java -Xms1024m -Xmx1024m -cp ${classpath} ${debug_args} \
com.novaordis.gld.cca.Main ${args} ${output_command_line_arg}


